import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, Search, ShoppingBasket, Sparkles, UserRound, ArrowRight, ChevronRight, Bell, MapPin, Plus, Check, X, SlidersHorizontal, Share2, TrendingDown, PackageCheck, ScanLine, ChevronLeft} from 'lucide-react';
import './styles.css';

const products=[
 {id:'butter',name:'Máslo Madeta 250 g',price:'39,90 Kč',usual:'57,90 Kč',off:'−31 %',tag:'Výborná cena',shop:'Lidl',emoji:'🧈',tone:'butter'},
 {id:'chicken',name:'Kuřecí prsní řízky',price:'129 Kč/kg',usual:'169 Kč/kg',off:'−24 %',tag:'Výborná cena',shop:'Kaufland',emoji:'🍗',tone:'chicken'},
 {id:'eggs',name:'Vejce M · 10 ks',price:'34,90 Kč',usual:'42,90 Kč',off:'−19 %',tag:'Dobrá cena',shop:'Kaufland',emoji:'🥚',tone:'eggs'}
];
const stores=['Lidl','Kaufland','Tesco','Albert','Penny','Billa','Rohlík'];
const cats=['Maso','Mléčné výrobky','Pečivo','Ovoce a zelenina','Nápoje','Drogerie','Sladkosti','Domácnost'];
function App(){const [page,setPage]=useState('onboard'),[step,setStep]=useState(0),[selected,setSelected]=useState([]),[query,setQuery]=useState(''),[detail,setDetail]=useState(null),[two,setTwo]=useState(false),[grill,setGrill]=useState(false),[notice,setNotice]=useState(true),[loading,setLoading]=useState(false);
 const toggle=x=>setSelected(s=>s.includes(x)?s.filter(i=>i!==x):[...s,x]); const go=p=>{setLoading(true);setTimeout(()=>{setPage(p);setLoading(false)},260)};
 if(page==='onboard')return <Onboard step={step} setStep={setStep} selected={selected} toggle={toggle} finish={()=>go('home')}/>;
 const active=page==='detail'?'search':page;
 return <div className="shell"><div className="phone"><header className="topbar">{page==='detail'||page==='grill'?<button className="back" onClick={()=>go(page==='grill'?'inspire':'search')}><ChevronLeft/></button>:<div className="berto"><i>◒</i>Berto</div>}<div className="top-actions">{page==='home'&&<button className="round" onClick={()=>setNotice(!notice)}><Bell size={19}/>{notice&&<b/>}</button>}<div className="avatar">KS</div></div></header>{loading?<Loading/>:<main className="screen">{page==='home'&&<HomePage open={go} detail={setDetail}/>} {page==='search'&&<SearchPage query={query} setQuery={setQuery} select={x=>{setDetail(x);go('detail')}}/>}{page==='detail'&&<Detail item={detail||products[0]}/>} {page==='basket'&&<Basket two={two} setTwo={setTwo}/>} {page==='inspire'&&<Inspire grill={()=>go('grill')}/>} {page==='grill'&&<Grill/>}{page==='profile'&&<Profile/>}</main>} {notice&&page==='home'&&<div className="notification"><div className="n-icon">☕</div><div><b>Tvoje oblíbená káva zlevnila</b><span>Jacobs Kronung právě o 35 %</span></div><button onClick={()=>setNotice(false)}><X size={15}/></button></div>}<nav className="bottomnav">{[["home",Home,'Domů'],['search',Search,'Hledat'],['basket',ShoppingBasket,'Košík'],['inspire',Sparkles,'Inspirace'],['profile',UserRound,'Profil']].map(([id,I,label])=><button key={id} className={active===id?'active':''} onClick={()=>go(id)}><I size={21}/><span>{label}</span></button>)}</nav></div></div>}
function Onboard({step,setStep,selected,toggle,finish}){const isStore=step===1, list=isStore?stores:cats;return <div className="shell"><div className="phone onboard"><div className="progress"><i style={{width:`${(step+1)*33}%`}}/></div>{step===0?<><div className="on-orb"></div><div className="intro-brand"><i>◒</i> Berto</div><div className="on-art"><span>129<small>Kč</small></span><b>✓</b><em>−31 %</em></div><section className="intro"><p className="eyebrow">Nakupuj s přehledem</p><h1>Zjisti, kdy se opravdu <strong>vyplatí koupit.</strong></h1><p>Berto sleduje ceny potravin, pozná falešné slevy a doporučí ti nejlepší obchod pro tvůj nákup.</p></section><button className="big-cta" onClick={()=>setStep(1)}>Začít <ArrowRight/></button><small className="skip">Bez registrace. Nastavení zabere pár vteřin.</small></>:<><header className="on-head"><button onClick={()=>setStep(step-1)}><ChevronLeft/></button><b>Krok {step} ze 2</b><span/></header><section className="picker"><p className="eyebrow">Aby Berto věděl, co hlídat</p><h1>{isStore?'Kde obvykle nakupuješ?':'Co se u tebe doma nakupuje?'}</h1><p>{isStore?'Vyber obchody ve svém okolí. Můžeš je kdykoliv změnit.':'Vyber oblíbené kategorie. Díky nim budou doporučení přesnější.'}</p><div className="chips">{list.map(x=><button className={selected.includes(x)?'selected':''} onClick={()=>toggle(x)} key={x}>{selected.includes(x)&&<Check size={15}/>} {x}</button>)}</div></section><button className="big-cta" onClick={()=>step===1?setStep(2):finish()}>{step===1?'Pokračovat':'Zobrazit Berto'} <ArrowRight/></button><button className="later" onClick={()=>step===1?setStep(2):finish()}>Přeskočit</button></>}</div></div>}
function HomePage({open,detail}){return <><section className="greeting"><p>Úterý, 15. července</p><h1>Ahoj, dnes se vyplatí <em>nakoupit chytře.</em></h1></section><button className="best-store" onClick={()=>open('basket')}><span className="best-label">NEJLEPŠÍ OBCHOD PRO TEBE TENTO TÝDEN</span><div className="store-line"><div className="store-logo">K</div><h2>Kaufland</h2><ChevronRight/></div><div className="saving"><span>Odhadovaná úspora</span><b>328 Kč</b></div><div className="store-button">Zobrazit nákup <ArrowRight size={16}/></div></button><SectionTitle title="Právě se vyplatí" action="Vše"/ ><div className="product-row">{products.map(p=><Product item={p} key={p.id} onClick={()=>{detail(p);open('detail')}}/>)}</div><SectionTitle title="Raději nekupovat"/><div className="avoid"><div className="avoid-icon">☕</div><div><b>Káva 500 g</b><span>Aktuálně dražší než obvykle</span></div><span className="wait">Počkej</span></div><div className="avoid"><div className="avoid-icon oil">🫒</div><div><b>Olivový olej</b><span>Pravděpodobně brzy zlevní</span></div><span className="wait">Počkej</span></div></>}
function SectionTitle({title,action}){return <div className="section-title"><h2>{title}</h2>{action&&<button>{action} <ChevronRight size={15}/></button>}</div>}
function Product({item,onClick}){return <button className="product" onClick={onClick}><div className={'prod-art '+item.tone}><span>{item.emoji}</span><b>{item.off}</b></div><small>{item.shop}</small><h3>{item.name}</h3><strong>{item.price}</strong><del>{item.usual}</del><em>{item.tag}</em></button>}
function SearchPage({query,setQuery,select}){const results=query?[...products,{name:'Káva Jacobs 500 g',price:'169 Kč',usual:'219 Kč',off:'−23 %',tag:'Dobrá cena',shop:'Tesco',emoji:'☕',tone:'coffee'}].filter(x=>x.name.toLowerCase().includes(query.toLowerCase())):[];return <><section className="search-intro"><p className="eyebrow">Ceny bez hádání</p><h1>Co chceš najít?</h1></section><label className="searchbox"><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hledej produkt, značku nebo kategorii"/>{query&&<button onClick={()=>setQuery('')}><X size={17}/></button>}</label>{!query?<><p className="smallcap">ZKUS HLEDAT</p><div className="examples">{['Máslo Madeta 250 g','Kuřecí prsa','Káva Jacobs 500 g'].map((x,i)=><button key={x} onClick={()=>setQuery(x)}><span>{['🧈','🍗','☕'][i]}</span>{x}<ChevronRight size={16}/></button>)}</div><div className="scan-card"><ScanLine/><div><b>Naskenuj čárový kód</b><p>Hned zjistíš, jestli je cena fér.</p></div></div></>:<><p className="smallcap">VÝSLEDKY ({results.length})</p>{results.map((p,i)=><button className="search-result" key={i} onClick={()=>select(p)}><span className={'mini-art '+p.tone}>{p.emoji}</span><div><b>{p.name}</b><small>Nejlevněji v {p.shop}</small></div><strong>{p.price}</strong></button>)}{results.length===0&&<Empty/>}</>}</>}
function Detail({item}){return <><div className="detail-product"><div className={'detail-art '+item.tone}>{item.emoji}</div><div><small>Máslo · 250 g</small><h1>{item.name}</h1><span className="verified"><Check size={12}/> Cena ověřena dnes</span></div></div><section className="price-card"><div><span>NEJLEPŠÍ CENA DNES</span><h2>{item.price}</h2><p>v <b>{item.shop}</b></p></div><div className="score"><b>92</b><span>/100</span><small>Cenové skóre</small></div></section><section className="ai-card"><div className="ai-dot"><Sparkles size={17}/></div><p><b>Výborná koupě.</b> Aktuální cena je o 31 % nižší než dlouhodobý průměr a patří mezi nejlepší ceny za posledních 6 měsíců.</p></section><div className="chart-head"><div><h2>Vývoj ceny</h2><p>Posledních 12 měsíců</p></div><span><TrendingDown size={14}/> −31 %</span></div><div className="chart"><div className="gridlines"/><svg viewBox="0 0 340 120" preserveAspectRatio="none"><path d="M0 38 C18 45 24 30 43 36 S70 51 91 48 S123 63 142 58 S172 80 191 77 S215 91 235 77 S263 84 281 54 S304 61 340 25" fill="none" stroke="#caff3b" strokeWidth="3"/><path d="M0 38 C18 45 24 30 43 36 S70 51 91 48 S123 63 142 58 S172 80 191 77 S215 91 235 77 S263 84 281 54 S304 61 340 25 L340 120 L0 120Z" fill="url(#g)"/><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#caff3b" stopOpacity=".28"/><stop offset="1" stopColor="#caff3b" stopOpacity="0"/></linearGradient></defs></svg><div className="chart-labels"><span>srp 25</span><span>lis</span><span>úno 26</span><span>kvě</span><span>čvc</span></div></div><div className="stats"><div><span>Běžná cena</span><b>57,90 Kč</b></div><div><span>Nejnižší za 12 měs.</span><b>36,90 Kč</b></div></div><SectionTitle title="Porovnání obchodů"/><div className="shops">{[['Lidl','39,90 Kč'],['Kaufland','42,90 Kč'],['Tesco','49,90 Kč'],['Albert','54,90 Kč'],['Rohlík','59,90 Kč']].map(([n,p],i)=><div key={n}><span className={'dotshop d'+i}>{n[0]}</span><b>{n}</b>{i===0&&<em>Nejlepší</em>}<strong>{p}</strong></div>)}</div><button className="alert-btn"><Bell size={18}/> Upozornit při poklesu ceny</button></>}
function Basket({two,setTwo}){const rows=two?[['Kaufland + Lidl','1 185 Kč'],['Kaufland','1 240 Kč'],['Lidl','1 310 Kč'],['Tesco','1 425 Kč']]:[['Kaufland','1 240 Kč'],['Lidl','1 310 Kč'],['Tesco','1 425 Kč'],['Albert','1 480 Kč']];return <><section className="basket-head"><p className="eyebrow">Můj chytrý nákup</p><h1>Tvůj košík</h1><p>6 uložených produktů · ceny z dnešních letáků</p></section><div className="toggle"><button className={!two?'active':''} onClick={()=>setTwo(false)}>Jeden obchod</button><button className={two?'active':''} onClick={()=>setTwo(true)}>Kombinace dvou</button></div><section className="basket-win"><PackageCheck/><div><span>NEJLEPŠÍ VOLBA</span><h2>{two?'Kaufland + Lidl':'Kaufland'}</h2><p>Oproti tvému běžnému obchodu ušetříš přibližně <b>{two?'295':'240'} Kč.</b></p></div></section><div className="basket-list">{rows.map(([n,p],i)=><div key={n} className={i===0?'winner':''}><span>{i+1}</span><b>{n}</b>{i===0&&<em>Nejlepší volba</em>}<strong>{p}</strong></div>)}</div><div className="basket-items"><div><b>V košíku</b><button><Plus size={15}/> Přidat</button></div><p>🥛 Mléko · 🥚 Vejce · 🍗 Kuřecí prsa · ☕ Káva · 🍝 Těstoviny · 🥣 Jogurty</p></div></>}
function Inspire({grill}){const cards=[['🔥','Grilovačka'],['🎉','Párty'],['🍲','Rodinná večeře'],['🏡','Víkend na chatě'],['🛒','Týdenní nákup'],['🍳','Vaření do 1 500 Kč']];return <><section className="inspire-head"><p className="eyebrow">NÁKUP PODLE SITUACE</p><h1>Co dnes <em>plánuješ?</em></h1><p>Berto složí chytrý nákup a najde nejvýhodnější cestu.</p></section><div className="inspire-grid">{cards.map(([e,n],i)=><button onClick={i===0?grill:undefined} key={n}><span>{e}</span><b>{n}</b><ChevronRight size={16}/></button>)}</div><div className="inspire-note"><Sparkles/><p><b>Žádné recepty naslepo.</b> Inspirace vždy vychází z aktuálních cen a akcí ve tvém okolí.</p></div></>}
function Grill(){return <><section className="grill-hero"><span>🔥</span><p className="eyebrow">TVŮJ CHYTRÝ PLÁN</p><h1>Grilovačka pro 8 lidí <em>do 2 500 Kč</em></h1></section><section className="grill-save"><span>Kaufland + Lidl</span><b>Ušetříš až 460 Kč</b></section><div className="meal-list">{[['🍗','Maso','Kuřecí, klobásy, steak'],['🥬','Zelenina','Kukuřice, paprika, salát'],['🥖','Pečivo','Bagety a toustový chléb'],['🥫','Omáčky','Kečup, hořčice, dip'],['🍺','Pivo a nealko','Pivo, limonáda, voda'],['🪵','Uhlí','Brikety na gril']].map(([e,n,d],i)=><div key={n}><span>{e}</span><div><b>{n}</b><small>{d}</small></div><strong>{[690,245,119,98,448,169][i]} Kč</strong><Check size={17}/></div>)}</div><button className="big-cta"><ShoppingBasket size={19}/> Přidat do košíku</button></>}
function Profile(){return <><section className="profile-top"><div className="big-avatar">KS</div><p className="eyebrow">KAROLÍNA SKOUFI</p><h1>Tvoje nákupní IQ</h1><div className="iq"><b>84</b><span>/100</span></div><p>Jsi v top 18 % chytrých nakupujících.</p></section><div className="profile-stats"><div><b>680 Kč</b><span>ušetřeno tento měsíc</span></div><div><b>4 týdny</b><span>chytrých nákupů v řadě</span></div><div><b>12</b><span>výhodných nákupů</span></div><div><b>3</b><span>odhalené falešné slevy</span></div></div><SectionTitle title="Tvoje odznaky"/><div className="badges">{[['◉','Lovec cen'],['⌁','Cenový sniper'],['☾','Měsíc bez přeplacení'],['✦','Ušetřeno 1 000 Kč']].map(([i,t],n)=><div className={n===3?'locked':''} key={t}><span>{i}</span><b>{t}</b></div>)}</div><button className="share"><Share2 size={18}/><span><b>Tento měsíc jsem díky Berto<br/>ušetřil 680 Kč.</b><small>Sdílet kartu</small></span><ChevronRight/></button></>}
function Empty(){return <div className="empty"><Search/><b>Nic jsme nenašli</b><p>Zkus jiný název nebo značku.</p></div>}; function Loading(){return <div className="loading"><i>◒</i><span>Hledám nejlepší ceny…</span></div>};createRoot(document.getElementById('root')).render(<App/>);
